### ISSUE TITLE
GRAI check digit 

### ISSUE THREAD

**Issue by RalphTro** [gs1/GS1_DigitalLink_Resolver_CE#15]
I just inserted a GRAI via the UI on https://data.gs1.org/ui/ 

When I tried to resolve this GRAI, I got the following response: 
{ error: "Error: INVALID CHECK DIGIT:  An invalid check digit was found for the primary identification key (8003)04012345111118 ; the correct check digit should be 7 at position 13" }

This is IMO not true, for two reasons: first, the check digit of a GRAI appears at position 14, not 13. See GS1 Gen Specs, section 3.9.3 for further details. It is correct that, strictly speaking, a GRAI without a serial number component is 13 digits long, but the GRAI needs to be prefixed with a zero, which results in 14 digits in total). Second, the check digit is 8, not 7. See https://www.gs1.org/services/check-digit-calculator for verification.    

Thanks in advance for fixing that.

Kind regards, 
Ralph

**Comment by nicklansley** [comment]
Hi Ralph

Apologies for the delay in responding - this is the Community Edition! No worries, could you try again - and if it fails, please could you attach your upload file here and I will take a look. 

Cheers
Nick

**Comment by philarcher** [comment]
Tidying up old issues. This was done ages ago.
