### ISSUE TITLE
Support for GRAI

### ISSUE THREAD

**Issue by RalphTro** [gs1/GS1_DigitalLink_Resolver_CE#3]
Thanks a lot for this great work so far! 
Would you mind adding support for the Global Returnable Asset Identifier (**GRAI**) as well? In this regard, I suggest that the resolver supports GRAIs with *and* without the serial number part, i.e. a web request for e.g. https://id.gs1.org/grai/04012345111119345 should provide both data/services applicable for a given instance (in this case, identified with serial number: '345') as well as data/service applicable for the GRAI ('04012345111119'). 
Thanks a lot in advance!

**Comment by philarcher** [comment]
Tidying up old issues. This was done ages ago.
