### ISSUE TITLE
Cannot access API

### ISSUE THREAD

**Issue by ablears** [gs1/GS1_DigitalLink_Resolver_CE#65]
Hi, thanks for providing this community edition. 

I am using the Postman collection based on the [API docs](https://documenter.getpostman.com/view/10078469/TVejgpjz#a81f038b-1c21-4b23-b6ea-1a79633a65e5) to send a test POST to {{base_url}}/resolver using the provided example.

I set the Authorization to Bearer Token with value MyAdminAuthKey as specified in resolver_data_entry_server/Dockerfile.

However, this is not successful.
`{"success":false,"error":"Unauthorized Access (Forbidden)"}`

I found I can access the ADMIN endpoints without issue, for example `GET {{base_url}}/admin/heardbuildsyncservers`.
And for the other endpoints it's a mix of OK and error, for example:

- GET {{base_url}}/resolver/all/count - Forbidden
- GET {{base_url}}/redirect/all - "error": "You are not authorize to access this endpoint"
- GET {{base_url}}/reference/linktypes - 200 OK

Can anyone point me in the right direction to fix this?

**Comment by nicklansley** [comment]
Hi, apologies for the delay in replying

/resolver and /redirect APIS need you to use an authorization key that matches one in the accounts table.
ADMIN authorization only works for the ADMIN APIs.

I hope this helps!
