### ISSUE TITLE
Resolver re-directs to wrong URL's

### ISSUE THREAD

**Issue by danieldu93** [gs1/GS1_DigitalLink_Resolver_CE#68]
I'm experiencing issue with the CE Resolver  (v1.1) and it is no longer re-directing to the expected location, please see the example below:

GTIN: 047400681002

1. Context = US; language = EN; URL = https://gillette.com/en-us/products/gillette-labs/exfoliating-bar-razor-by-gillette
2. Context = CA; language = EN; URL = https://gillette.ca/exfoliating-bar-razor-by-gillette

based on the testing we performed on Monday 30.10.2023 it worked as expected - smartfone in US would be taken to gillette.com website while someone scanning in Canada will be taken to gillette.ca website

Currently no matter of the context/language the user is always taken to gillette.com (case number 1) website, which is not the intented behaviour. 

We have tried to set the defaultcontext and defaultianalanguage parameters but no luck.

Please advise and help !

Thank you!

**Comment by nicklansley** [comment]
Apologies for this I am now focussed on Resolver v3.0 and I have stopped maintenance on v2.6. I hope you find the far simpler v3.0 to your liking!
