### ISSUE TITLE
Missing health probes

### ISSUE THREAD

**Issue by erik-wramner** [gs1/GS1_DigitalLink_Resolver_CE#71]
We need health probes (liveness and readiness) for Kubernetes and for a fronting load balancer for the core resolver components. We don't care as much about data entry, but the customer-facing resolver and the toolkit it depends on must have probes.

Will provide a pull request.

**Comment by erik-wramner** [comment]
See #72 which fixes this.

**Comment by nicklansley** [comment]
Apologies for this I am now focussed on Resolver v3.0 and I have stopped maintenance on v2.6. I hope you find the far simpler v3.0 to your liking!
