### ISSUE TITLE
GS1 Digital Link, Key qualifiers Path element order

### ISSUE THREAD

**Issue by nerixs** [gs1/GS1_DigitalLink_Resolver_CE#81]
Hello,
The documentation "GS1 Digital Link Standard: URI Syntax" chapter 4.9 Path element order, gives the example below:

The rule for gtin-path would permit any of these:
/01/09520123456788/22/2A/10/ABC123/21/12345XYZ
/01/09520123456788/10/ABC123/
/01/09520123456788/10/ABC123/21/12345XYZ
/01/09520123456788/21/12345XYZ

But does not permit strings such as:
/01/09520123456788/21/12345XYZ/10/ABC123

Are we to understand that there is an order to be respected when creating the link?
What rule defies this order?

The following classification seems to have been accepted in the tests carried out:
N°1 : cpv-code = "22" ; Consumer Product Variant
N°2: lot-code = "10" ; Batch/Lot identifier
N°3: ser-code = "21" ; GTIN Serial Number

Does the order of the other Key qualifiers "8011, 254, 8020, 8019, 235 and 7040" also matter?

Thanks for your explanations.

**Comment by tonnelier** [comment]
Fyi,

 

The first part of the GS1 Digital Link has a hierarchy, 

from domain, gtin(01), cpv, batch, to serial(21) in this order

any other parameter (?variable=value then &variable=value) do not have any order

 

Cordialement.
______________
Laurent Tonnelier
President, mobiLead sas
 ***@***.***> ***@***.***
  <http://mobilead.eu/wp-content/uploads/2016/10/mobiLead-768x155.png> 

Les informations contenues dans ce courriel, et ses pièces jointes, sont strictement confidentielles et réservées à l'usage exclusif des personnes identifiées comme destinataires. Si vous avez reçu ce courriel par erreur, veuillez y répondre afin de nous en informer, avant de le supprimer ainsi que toutes ses pièces-jointes. La copie sans autorisation, comme le transfert de ce courriel vers un autre destinataire, sont illégaux.

 

From: nerixs ***@***.***> 
Sent: Friday, January 19, 2024 10:34 AM
To: gs1/GS1_DigitalLink_Resolver_CE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gs1/GS1_DigitalLink_Resolver_CE] GS1 Digital Link, Key qualifiers Path element order (Issue #81)

 

Hello,
The documentation "GS1 Digital Link Standard: URI Syntax" chapter 4.9 Path element order, gives the example below:

The rule for gtin-path would permit any of these:
/01/09520123456788/22/2A/10/ABC123/21/12345XYZ
/01/09520123456788/10/ABC123/
/01/09520123456788/10/ABC123/21/12345XYZ
/01/09520123456788/21/12345XYZ

But does not permit strings such as:
/01/09520123456788/21/12345XYZ/10/ABC123

Are we to understand that there is an order to be respected when creating the link?
What rule defies this order?

The following classification seems to have been accepted in the tests carried out:
N°1 : cpv-code = "22" ; Consumer Product Variant
N°2: lot-code = "10" ; Batch/Lot identifier
N°3: ser-code = "21" ; GTIN Serial Number

Does the order of the other Key qualifiers "8011, 254, 8020, 8019, 235 and 7040" also matter?

Thanks for your explanations.

**Comment by nerixs** [comment]
Thank you for these explanations!
Best regards

**Comment by tonnelier** [comment]
: is a reserved word for port number
' is not a safe URL character neither

**Comment by nerixs** [comment]
Hello,
That's a good one! Thank you very much.
But that doesn't seem to be the only problem.
https://id.gs1.org/01/01234567890128?235=5vBZr-AjR8!5Sm&8008=19052001
Tested on:
https://digital-link.evrythng.com/verifier

**Comment by terryburton** [comment]
Refer to the GS1 DL URI Syntax grammar.

AI (235) is only recognised in the context of a key-qualifier (in the path info) for AI (01), whereas it is specified as a regular attribute (in the query parameters) in your data.

> **Aside:** Hypothetically, assuming that (235) where a valid attribute then the following would apply: If an AI would be valid anywhere within the current key-qualifier sequence for the primary key, it shall only appear as a key qualifier within the URI path segment and shall not appear as an attribute within the query string. The notion being that AI that supplement the key data in order to serialise / identify a unique item instance, shall be represented as key qualifiers: The path info identifies the "thing"; the query parameters describe it.

So you likely mean:

```
https://id.gs1.org/01/01234567890128/235/5vBZr-AjR8%215%27S%3Am?8008=19052001
```

For future reference, the [GS1 Syntax Engine](https://www.gs1.org/standards/gs1-barcodes/gs1-barcode-syntax-resource) can extract AI elements from scan and transform these into a number of different representations, including GS1 Digital Link URIs.

DotCode is not currently supported, so in this instance you need to provide the scan data under a supported "FNC1 in first" AIM Symbology Identifier such as GS1 QR Code ("`]Q3`"). (The rules for the scan data transfer protocol are the same, including normalisation of DotCode's inverted use of FNC in first with leading numeric data.)

Just enter the following and click "Process input data":

```
]Q32355vBZr-AjR8!5'S:m{GS}0101234567890128800819052001
```

**Comment by nicklansley** [comment]
Apologies for this I am now focussed on Resolver v3.0 and I have stopped maintenance on v2.6. I hope you find the far simpler v3.0 to your liking!

**Comment by terryburton** [comment]
> DotCode is not currently supported, so in this instance you need to provide the scan data under a supported "FNC1 in first" AIM Symbology Identifier such as GS1 QR Code ("`]Q3`"). (The rules for the scan data transfer protocol are the same, including normalisation of DotCode's inverted use of FNC in first with leading numeric data.)

Support for processing DotCode scandata message has just been added to the Barcode Syntax Engine with [ecda336](https://github.com/gs1/gs1-syntax-engine/commit/ecda336ca08ec758e010f088948847212765a135).
